question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]

# question_data = [
#     {"category": "General Knowledge",
#      "type": "multiple", "difficulty": "easy",
#      "question": "What is the largest organ of the human body?",
#      "correct_answer": "Skin",
#      "incorrect_answers": ["Heart", "large Intestine", "Liver"]},
#     {"category": "Mythology", "type": "multiple", "difficulty": "easy",
#      "question": "This Greek goddess&#039;s name was chosen for the dwarf planet responsible for discord on Pluto&#039;s classification amongst astronomers.",
#      "correct_answer": "Eris", "incorrect_answers": ["Charon", "Ceres", "Dysnomia"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "Luigi is taller than Mario?", "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Geography", "type": "multiple", "difficulty": "easy",
#      "question": "How many time zones does China have?", "correct_answer": "1",
#      "incorrect_answers": ["3", "4", "2"]},
#     {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
#      "question": "How many bones are in the human body?", "correct_answer": "206",
#      "incorrect_answers": ["203", "209", "200"]},
#     {"category": "Geography", "type": "multiple", "difficulty": "easy",
#      "question": "What country has a horizontal bicolor red and white flag?",
#      "correct_answer": "Monaco",
#      "incorrect_answers": ["Bahrain", "Malta", "Liechenstein"]},
#     {"category": "Geography", "type": "multiple", "difficulty": "easy",
#      "question": "Which of these is the name of the largest city in the US state Tennessee?",
#      "correct_answer": "Memphis", "incorrect_answers": ["Thebes", "Alexandria", "Luxor"]},
#     {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
#      "question": "What company develops the Rock Band series of rhythm games?", "correct_answer": "Harmonix",
#      "incorrect_answers": ["Activision", "Konami", "Electronic Arts"]},
#     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
#      "question": "When you cry in space, your tears stick to your face.", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Board Games", "type": "multiple", "difficulty": "easy",
#      "question": "Which one of these is not a real game in the Dungeons &amp; Dragons series?",
#      "correct_answer": "Extreme Dungeons &amp; Dragons",
#      "incorrect_answers": ["Advanced Dungeons &amp; Dragons", "Dungeons &amp; Dragons 3.5th edition",
#                            "Advanced Dungeons &amp; Dragons 2nd edition"]},
#     {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
#      "question": "Which Pokemon generation did the fan-named &quot;Masuda Method&quot; first appear in? ",
#      "correct_answer": "Diamond\/Pearl", "incorrect_answers": ["Ruby\/Sapphire", "Black\/White", "X\/Y"]},
#     {"category": "Mythology", "type": "multiple", "difficulty": "easy",
#      "question": "Which figure from Greek mythology traveled to the underworld to return his wife Eurydice to the land of the living?",
#      "correct_answer": "Orpheus", "incorrect_answers": ["Hercules", "Perseus", "Daedalus"]},
#     {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
#      "question": "Which of the following was NOT a playable character in the game Kingdom Hearts: Birth by Sleep?",
#      "correct_answer": "Ignis", "incorrect_answers": ["Ventus", "Terra", "Aqua"]},
#     {"category": "Sports", "type": "multiple", "difficulty": "easy",
#      "question": "Which city did the former NHL team &quot;The Nordiques&quot; originiate from?",
#      "correct_answer": "Quebec City", "incorrect_answers": ["Houston", "Montreal", "New York"]},
#     {"category": "Entertainment: Television", "type": "multiple", "difficulty": "easy",
#      "question": "Who won Big Brother 2014 UK?", "correct_answer": "Helen Wood",
#      "incorrect_answers": ["Christopher Hall", "Pauline Bennett", "Pavandeep &quot;Pav&quot; Paul"]},
#     {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
#      "question": "How tall is the Burj Khalifa?", "correct_answer": "2,722 ft",
#      "incorrect_answers": ["2,717 ft", "2,546 ft", "3,024 ft"]},
#     {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
#      "question": "Kiznaiver is an adaptation of a manga.", "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Board Games", "type": "multiple", "difficulty": "easy",
#      "question": "In which year was the pen and paper RPG &quot;Deadlands&quot; released?",
#      "correct_answer": "1996",
#      "incorrect_answers": ["2003", "1999", "1993"]},
#     {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
#      "question": "Which member of the Velvet Room is not a playable character in Persona 4 Arena Ultimax?",
#      "correct_answer": "Theodore", "incorrect_answers": ["Elizabeth", "Margaret", "Marie"]},
#     {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
#      "question": "Foie gras is a French delicacy typically made from what part of a duck or goose?",
#      "correct_answer": "Liver", "incorrect_answers": ["Heart", "Stomach", "Intestines"]}
# ]
